version: 2

models:
  - name: stg_sales__brands
    description: This model contains all bike brands sold in Local Bike stores
    columns:
      - name: brand_id
        description: This is a unique identifier for the brand
        data_tests:
          - unique
          - not_null

  - name: stg_sales__categories
    description: This model contains all bike categories sold in Local Bike stores
    columns:
      - name: category_id
        description: This is a unique identifier for the category
        data_tests:
          - unique
          - not_null

  - name: stg_sales__customers
    description: This model contains all Local Bike store customers
    columns:
      - name: customer_id
        description: This is a unique identifier for the customer
        data_tests:
          - unique
          - not_null

  - name: stg_sales__order_items
    description: This model contains all items included in each command
    columns:
      - name: order_item_id
        description: This is a unique identifier for the order item
        data_tests:
          - unique
          - not_null
      - name: order_id
        description: This is a unique identifier for the order
        data_tests:
          - not_null
      - name: product_id
        description: This is a unique identifier for the product
        data_tests:
          - not_null

  - name: stg_sales__orders
    description: This model contains all orders
    columns:
      - name: order_id
        description: This is a unique identifier for the order
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: This is a unique identifier for the customer
        data_tests:
          - not_null
      - name: store_id
        description: This is a unique identifier for the store
        data_tests:
          - not_null
      - name: staff_id
        description: This is a unique identifier for the staff
        data_tests:
          - not_null

  - name: stg_sales__products
    description: This model contains all products sold in Local Bike stores
    columns:
      - name: product_id
        description: This is a unique identifier for the product
        data_tests:
          - unique
          - not_null
      - name: brand_id
        description: This is a unique identifier for the brand
        data_tests:
          - not_null
      - name: category_id
        description: This is a unique identifier for the category
        data_tests:
          - not_null

  - name: stg_sales__staffs
    description: This model contains all Local Bike staffs
    columns:
      - name: staff_id
        description: This is a unique identifier for the staff
        data_tests:
          - unique
          - not_null
      - name: store_id
        description: This is a unique identifier for the store
        data_tests:
          - not_null
      - name: manager_id
        description: This is a unique identifier for the manager

  - name: stg_sales__stocks
    description: This model contains all Local Bike stocks
    columns:
      - name: stock_id
        description: This is a unique identifier for the staff
        data_tests:
          - unique
          - not_null
      - name: store_id
        description: This is a unique identifier for the store
        data_tests:
          - not_null
      - name: product_id
        description: This is a unique identifier for the product

  - name: stg_sales__stores
    description: This model contains all Local Bike stores
    columns:
      - name: store_id
        description: This is a unique identifier for the store
        data_tests:
          - unique
          - not_null